FROM alpine-java:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY product-service/target/product-service-0.0.1-SNAPSHOT.jar /opt/lib/
COPY productservice-entrypoint.sh /opt/bin/
RUN chmod 755 /opt/bin/productservice-entrypoint.sh
EXPOSE 8080

